baseURL = 'https://doctornfx.github.io/'
languageCode = 'en-us'
title = 'Doctor.N FX'
theme = 'PaperMod'

[params]
description = "Free and open source audio plugins"
author = "Doctor.N FX"
defaultTheme = "auto"  # auto, light, dark

[params.label]
text = "Doctor.N FX"
icon = "/logo.png"  # Path to your logo
iconHeight = 35  # Adjust height as needed
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true

[[params.socialIcons]]
name = "kofi"
url = "https://ko-fi.com/doctornfx"

[[params.socialIcons]]
name = "bluesky"
url = "https://bsky.app/profile/doctornfx.bsky.social"

[[params.socialIcons]]
name = "discord"
url = "https://discord.gg/yourinvite"

[[params.socialIcons]]
name = "github"
url = "https://github.com/doctornfx"

[[params.socialIcons]]
name = "email"
url = "mailto:doctorn.fx@gmail.com"

[[menu.main]]
identifier = "plugins"
name = "Plugins"
url = "/plugins/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 20

[[menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/doctornfx"
weight = 30

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
tag = "tags"
category = "categories"
